# File name: docker-compose.yml
# Author: Queues Team
# Description: Defines the containers to be used when running docker-compose. 

version: '3.7'

services:
    ag-frontend:
        container_name: ag-frontend
        command: bash -c 'npm run start'
        ports: [3000:3000]
        volumes:
            - .:/app
            - /app/node_modules
        environment:
            - NODE_ENV=development
            - CHOKIDAR_USEPOLLING=true
        build:
            context: .
            dockerfile: Dockerfile
